language: php

php:
  - 7.1
  - 7.2

services: mongodb

before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv config-rm xdebug.ini
  - composer install

script: vendor/bin/phpunit -c tests/